### ISSUE TITLE
wrong loop range?

### ISSUE THREAD

**Issue by wenbin-lin** [AljazBozic/DeepDeform#3]
https://github.com/AljazBozic/DeepDeform/blob/6572f4e0df633dba342c1957b5cfe4b88985275d/evaluation/csrc/cpu/image_proc.cpp#L101
Is this line supposed to be
`for (int x = 1; x < width - 1; ++x) { `

**Comment by AljazBozic** [comment]
Thank you for noticing the bug! It was just corrected in the repository.
