### ISSUE TITLE
Masks of certain objects are missing?

### ISSUE THREAD

**Issue by dwxrycb123** [AljazBozic/DeepDeform#4]
Thank you for publishing this fantastic dataset!

The paper said that all dynamic objects that are found in certain frames are given unique instance ids and their masks are annotated.
But it seems that some object masks are missing,  "train_masks.json" says:
`    {
        "color": "train/seq000/color/000200.jpg",
        "depth": "train/seq000/depth/000200.png",
        "mask": "train/seq000/mask/000200.png",
        "seq_id": "seq000",
        "frame_id": "000200",
        "object_id": "blackdog"
    },`
and 
`    {
        "color": "train/seq000/color/000200.jpg",
        "depth": "train/seq000/depth/000200.png",
        "mask": "train/seq000/mask/000200.png",
        "seq_id": "seq000",
        "frame_id": "000200",
        "object_id": "lady"
    },`
, these two dictionaries refer to the same mask file while the file only illustrates the mask for the lady:
![image](https://user-images.githubusercontent.com/39766807/111405087-d5b89a80-870a-11eb-84be-5e210bed178c.png)

Is the mask for blackdog missing or I got something wrong here?

**Comment by AljazBozic** [comment]
Hi! Thank you for letting us know! The object masks for cases when there are multiple objects in the scene were not stored correctly, I'm sorry for all the trouble. I just sent an email with updated masks, now they should be complete. Let me know if you experience any other issues!
