### ISSUE TITLE
Dense correspondence between point clouds?

### ISSUE THREAD

**Issue by Sentient07** [AljazBozic/DeepDeform#6]
Hello,

Thanks for this amazing work. I was wondering whether there is dense ground truth information available between two point clouds? I see that there is a per-pixel displacement from optical flow. Is it possible to use this for establishing dense point-point map between two point clouds? Thank you!

**Comment by AljazBozic** [comment]
Hi,

I'm sorry for a very late reply. There is actually also scene flow available (in same format as optical flow), with a 3D flow field for every pixel. It can be combined with the provided depth maps to establish dense 3D correspondences. You would use the depth map and corresponding camera parameters to backproject the pixels into 3D points in source frame. Afterwards, the 3D scene flow can be applied to transform the points to the target frame.

Best,
Aljaz
