### ISSUE TITLE
How to control the number of vertices?

### ISSUE THREAD

**Issue by phamtrongthang123** [AljazBozic/DeepDeform#7]
Thank you for public this repo. 
In the code I see that we need to make sure the number of vertices the same between the source and the target mesh. However, for normal fusion process, the number of vertices will be changed. So I am wondering how will we control the number of vertices?

**Comment by AljazBozic** [comment]
Hi,

Yes, it's true that during fusion the canonical shape is continuously updated, and the number of vertices in extracted mesh changes every time. However, for evaluation of tracking we require consistent meshes (over specific frame segments, e.g. 0-100, 0-200, 0-300, etc.). To cope with that, in our framework we extract the latest canonical mesh at each segment's end (e.g. at frame 200), and we deform it to every evaluation frame, to get consistent meshes at evaluation frames (e.g. 0, 50, 100, 150, 200). 

Best,
Aljaz

**Comment by phamtrongthang123** [comment]
I see. Thank you very much.
