### ISSUE TITLE
Dataset link broken

### ISSUE THREAD

**Issue by Barbany** [AljazBozic/DeepDeform#8]
I filled out the form to get access to the dataset. While I got the link, it does not work and I'm unable to download it.

**Comment by AljazBozic** [comment]
I'm sorry for the troubles, the dataset (and the corresponding benchmark) was offline for over a week because of an issue with the web server. 

It should be resolved now, and you should have received an updated link to your submitted email. If not, please let me know.

**Comment by ShenghaoZhou** [comment]
The dataset link stopped working and it returned 404 error.
